export const data=[
  {
   "transmittalid": 1,
   "wonNo": "AS2012",
   "wonTitle": "OFFSHORE MAINTENANCE CONTRACT - WORK PACK PREPARATION FOR AKER SOLUTIONS",
   "transmittalNo": "tran-0",
   "date": "03\/02\/2022",
   "from": "CALVIN TAN CHIEW SENG",
   "to": "BSP SEBASTIAN FOO, AER\/77X",
   "transmittalDetailid": 1,
   "docNumbe": "Doc1",
   "description": "OFFSHORE MAINTENANCE CONTRACT - WORK PACK PREPARATION FOR AKER SOLUTIONS",
   "rev": "rev-0",
   "status": "IFC",
   "type": "ORIGINALS"
  },
  {
   "transmittalid": 1,
   "wonNo": "AS2012",
   "wonTitle": "OFFSHORE MAINTENANCE CONTRACT - WORK PACK PREPARATION FOR AKER SOLUTIONS",
   "transmittalNo": "tran-0",
   "date": "03\/02\/2022",
   "from": "CALVIN TAN CHIEW SENG",
   "to": "BSP SEBASTIAN FOO, AER\/77X",
   "transmittalDetailid": 2,
   "docNumbe": "Doc2",
   "description": "OFFSHORE MAINTENANCE CONTRACT - WORK PACK PREPARATION FOR AKER SOLUTIONS",
   "rev": "rev-1",
   "status": "IFC",
   "type": "ORIGINALS"
  },
  {
   "transmittalid": 1,
   "wonNo": "AS2012",
   "wonTitle": "OFFSHORE MAINTENANCE CONTRACT - WORK PACK PREPARATION FOR AKER SOLUTIONS",
   "transmittalNo": "tran-0",
   "date": "03\/02\/2022",
   "from": "CALVIN TAN CHIEW SENG",
   "to": "BSP SEBASTIAN FOO, AER\/77X",
   "transmittalDetailid": 3,
   "docNumbe": "Doc3",
   "description": "OFFSHORE MAINTENANCE CONTRACT - WORK PACK PREPARATION FOR AKER SOLUTIONS",
   "rev": "rev-2",
   "status": "IFC",
   "type": "ORIGINALS"
  },
  {
   "transmittalid": 1,
   "wonNo": "AS2012",
   "wonTitle": "OFFSHORE MAINTENANCE CONTRACT - WORK PACK PREPARATION FOR AKER SOLUTIONS",
   "transmittalNo": "tran-0",
   "date": "03\/02\/2022",
   "from": "CALVIN TAN CHIEW SENG",
   "to": "BSP SEBASTIAN FOO, AER\/77X",
   "transmittalDetailid": 4,
   "docNumbe": "Doc4",
   "description": "OFFSHORE MAINTENANCE CONTRACT - WORK PACK PREPARATION FOR AKER SOLUTIONS",
   "rev": "rev-3",
   "status": "IFC",
   "type": "ORIGINALS"
  },
  {
   "transmittalid": 1,
   "wonNo": "AS2012",
   "wonTitle": "OFFSHORE MAINTENANCE CONTRACT - WORK PACK PREPARATION FOR AKER SOLUTIONS",
   "transmittalNo": "tran-0",
   "date": "03\/02\/2022",
   "from": "CALVIN TAN CHIEW SENG",
   "to": "BSP SEBASTIAN FOO, AER\/77X",
   "transmittalDetailid": 5,
   "docNumbe": "Doc5",
   "description": "OFFSHORE MAINTENANCE CONTRACT - WORK PACK PREPARATION FOR AKER SOLUTIONS",
   "rev": "rev-4",
   "status": "IFC",
   "type": "ORIGINALS"
  },
  {
   "transmittalid": 2,
   "wonNo": "AS2222",
   "wonTitle": "OFFSHORE MAINTENANCE CONTRACT - WORK PACK PREPARATION FOR AKER SOLUTIONS",
   "transmittalNo": "tran-0",
   "date": "03\/02\/2022",
   "from": "CALVIN TAN CHIEW SENG",
   "to": "BSP SEBASTIAN FOO, AER\/77X",
   "transmittalDetailid": 6,
   "docNumbe": "Doc1",
   "description": "OFFSHORE MAINTENANCE CONTRACT - WORK PACK PREPARATION FOR AKER SOLUTIONS",
   "rev": "rev-0",
   "status": "IDC",
   "type": "ORIGINALS"
  },
  {
   "transmittalid": 2,
   "wonNo": "AS2222",
   "wonTitle": "OFFSHORE MAINTENANCE CONTRACT - WORK PACK PREPARATION FOR AKER SOLUTIONS",
   "transmittalNo": "tran-0",
   "date": "03\/02\/2022",
   "from": "CALVIN TAN CHIEW SENG",
   "to": "BSP SEBASTIAN FOO, AER\/77X",
   "transmittalDetailid": 7,
   "docNumbe": "Doc2",
   "description": "OFFSHORE MAINTENANCE CONTRACT - WORK PACK PREPARATION FOR AKER SOLUTIONS",
   "rev": "rev-1",
   "status": "IDC",
   "type": "ORIGINALS"
  },
  {
   "transmittalid": 2,
   "wonNo": "AS2222",
   "wonTitle": "OFFSHORE MAINTENANCE CONTRACT - WORK PACK PREPARATION FOR AKER SOLUTIONS",
   "transmittalNo": "tran-0",
   "date": "03\/02\/2022",
   "from": "CALVIN TAN CHIEW SENG",
   "to": "BSP SEBASTIAN FOO, AER\/77X",
   "transmittalDetailid": 8,
   "docNumbe": "Doc3",
   "description": "OFFSHORE MAINTENANCE CONTRACT - WORK PACK PREPARATION FOR AKER SOLUTIONS",
   "rev": "rev-2",
   "status": "IDC",
   "type": "ORIGINALS"
  },
  {
   "transmittalid": 2,
   "wonNo": "AS2222",
   "wonTitle": "OFFSHORE MAINTENANCE CONTRACT - WORK PACK PREPARATION FOR AKER SOLUTIONS",
   "transmittalNo": "tran-0",
   "date": "03\/02\/2022",
   "from": "CALVIN TAN CHIEW SENG",
   "to": "BSP SEBASTIAN FOO, AER\/77X",
   "transmittalDetailid": 9,
   "docNumbe": "Doc4",
   "description": "OFFSHORE MAINTENANCE CONTRACT - WORK PACK PREPARATION FOR AKER SOLUTIONS",
   "rev": "rev-3",
   "status": "IDC",
   "type": "ORIGINALS"
  },
  {
   "transmittalid": 2,
   "wonNo": "AS2222",
   "wonTitle": "OFFSHORE MAINTENANCE CONTRACT - WORK PACK PREPARATION FOR AKER SOLUTIONS",
   "transmittalNo": "tran-0",
   "date": "03\/02\/2022",
   "from": "CALVIN TAN CHIEW SENG",
   "to": "BSP SEBASTIAN FOO, AER\/77X",
   "transmittalDetailid": 10,
   "docNumbe": "Doc5",
   "description": "OFFSHORE MAINTENANCE CONTRACT - WORK PACK PREPARATION FOR AKER SOLUTIONS",
   "rev": "rev-4",
   "status": "IDC",
   "type": "ORIGINALS"
  }
 ];
  